import type { PuzzleDefinition, ValidatedPuzzle } from '../types';
import { colorId } from '../types';
import { validatePuzzleDefinition } from '../engine/validation';

/** B&W 15×15 puzzle: Anchor 15├ù15. */
// prettier-ignore
const anchorDefinition: PuzzleDefinition = {
  id: 'bw-anchor-15x15',
  name: 'Anchor 15├ù15',
  kind: 'bw',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [colorId('black'), colorId('black'), null, null, null, null, null, colorId('black'), null, null, null, null, null, colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), null, null, null, null, colorId('black'), null, null, null, null, colorId('black'), colorId('black'), colorId('black')],
    [null, colorId('black'), colorId('black'), colorId('black'), null, null, null, colorId('black'), null, null, null, colorId('black'), colorId('black'), colorId('black'), null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
  ],
  colClues: [
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 12, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
  ],
};

/** B&W 15×15 puzzle: Cat 15├ù15. */
// prettier-ignore
const catDefinition: PuzzleDefinition = {
  id: 'bw-cat-15x15',
  name: 'Cat 15├ù15',
  kind: 'bw',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [colorId('black'), null, null, null, null, null, null, null, null, null, null, null, null, null, colorId('black')],
    [colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), null, colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 15, colorId: colorId('black') }],
    [{ length: 15, colorId: colorId('black') }],
    [{ length: 15, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 15, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
  ],
  colClues: [
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 12, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
  ],
};

/** B&W 15×15 puzzle: House 15├ù15. */
// prettier-ignore
const houseDefinition: PuzzleDefinition = {
  id: 'bw-house-15x15',
  name: 'House 15├ù15',
  kind: 'bw',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null, colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null, colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null, colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
  ],
  colClues: [
    [],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [],
  ],
};

/** B&W 15×15 puzzle: Skull 15├ù15. */
// prettier-ignore
const skullDefinition: PuzzleDefinition = {
  id: 'bw-skull-15x15',
  name: 'Skull 15├ù15',
  kind: 'bw',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, null, colorId('black'), colorId('black'), null, colorId('black'), null, colorId('black'), null, colorId('black'), null, colorId('black'), colorId('black'), null, null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, null, null, colorId('black'), null, colorId('black'), null, colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), null, colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }],
  ],
  colClues: [
    [],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [],
  ],
};

/** B&W 15×15 puzzle: Tree 15├ù15. */
// prettier-ignore
const treeDefinition: PuzzleDefinition = {
  id: 'bw-tree-15x15',
  name: 'Tree 15├ù15',
  kind: 'bw',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
  ],
  colClues: [
    [],
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 14, colorId: colorId('black') }],
    [{ length: 15, colorId: colorId('black') }],
    [{ length: 14, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }],
    [],
  ],
};

/** Color 15×15 puzzle: Sailboat 15├ù15. */
// prettier-ignore
const boatDefinition: PuzzleDefinition = {
  id: 'color-boat-15x15',
  name: 'Sailboat 15├ù15',
  kind: 'color',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('white'), name: 'White', value: '#ffffff' }, { id: colorId('blue'), name: 'Blue', value: '#1e88e5' }, { id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('brown'), name: 'Brown', value: '#795548' }],
  solution: [
    [null, null, null, null, null, null, null, colorId('white'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('white'), colorId('white'), null, null, null, null, null, null, null],
    [null, null, null, null, null, colorId('white'), colorId('white'), colorId('white'), null, null, null, null, null, null, null],
    [null, null, null, null, colorId('white'), colorId('white'), colorId('white'), colorId('white'), null, null, null, null, null, null, null],
    [null, null, null, colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), null, null, null, null, null, null, null],
    [null, null, colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), null, null, null, null, null, null],
    [null, colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), colorId('white'), null, null, null, null, null],
    [null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, colorId('brown'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('brown'), null, null, null],
    [null, null, colorId('brown'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('brown'), null, null, null],
    [null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('white') }],
    [{ length: 2, colorId: colorId('white') }],
    [{ length: 3, colorId: colorId('white') }],
    [{ length: 4, colorId: colorId('white') }],
    [{ length: 5, colorId: colorId('white') }],
    [{ length: 7, colorId: colorId('white') }],
    [{ length: 9, colorId: colorId('white') }],
    [{ length: 9, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('brown') }, { length: 8, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('brown') }, { length: 8, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }],
    [{ length: 10, colorId: colorId('brown') }],
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 15, colorId: colorId('blue') }],
  ],
  colClues: [
    [{ length: 4, colorId: colorId('blue') }],
    [{ length: 1, colorId: colorId('white') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('white') }, { length: 4, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 5, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 6, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 7, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 1, colorId: colorId('white') }, { length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 1, colorId: colorId('brown') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('brown') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('blue') }],
  ],
};

/** Color 15×15 puzzle: Cherry 15├ù15. */
// prettier-ignore
const cherryDefinition: PuzzleDefinition = {
  id: 'color-cherry-15x15',
  name: 'Cherry 15├ù15',
  kind: 'color',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('green'), name: 'Green', value: '#43a047' }],
  solution: [
    [null, null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), null, colorId('green'), colorId('green'), null, colorId('red'), colorId('red'), null, null, null, null],
    [null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('green'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null],
    [null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), null, null, null, colorId('red'), colorId('red'), null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 1, colorId: colorId('green') }, { length: 5, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 4, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('red') }],
    [],
    [],
    [],
    [],
  ],
  colClues: [
    [],
    [{ length: 3, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }, { length: 3, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }, { length: 5, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }, { length: 6, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }, { length: 7, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }, { length: 6, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('green') }, { length: 4, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }],
    [],
    [],
  ],
};

/** Color 15×15 puzzle: Flower 15├ù15. */
// prettier-ignore
const flowerDefinition: PuzzleDefinition = {
  id: 'color-flower-15x15',
  name: 'Flower 15├ù15',
  kind: 'color',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }, { id: colorId('green'), name: 'Green', value: '#43a047' }],
  solution: [
    [null, null, null, null, null, null, null, colorId('red'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null],
    [null, null, null, null, colorId('red'), colorId('red'), null, colorId('yellow'), null, colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), null, colorId('yellow'), colorId('yellow'), colorId('yellow'), null, colorId('red'), colorId('red'), null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('yellow'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, null, null, null, colorId('red'), colorId('red'), null, colorId('yellow'), null, colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('green'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('green'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('green'), colorId('green'), null, colorId('green'), colorId('green'), null, null, null, null, null],
    [null, null, null, null, null, colorId('green'), null, null, null, colorId('green'), null, null, null, null, null],
    [null, null, null, null, colorId('green'), colorId('green'), null, null, null, colorId('green'), colorId('green'), null, null, null, null],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 3, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 5, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 3, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }, { length: 1, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
  ],
  colClues: [
    [],
    [],
    [],
    [{ length: 2, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 1, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 3, colorId: colorId('red') }, { length: 3, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('green') }],
    [{ length: 3, colorId: colorId('red') }, { length: 4, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }, { length: 3, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 3, colorId: colorId('red') }, { length: 3, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('red') }, { length: 1, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }],
    [],
    [],
  ],
};

/** Color 15×15 puzzle: Mushroom 15├ù15. */
// prettier-ignore
const mushroomDefinition: PuzzleDefinition = {
  id: 'color-mushroom-15x15',
  name: 'Mushroom 15├ù15',
  kind: 'color',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('white'), name: 'White', value: '#fdd835' }, { id: colorId('green'), name: 'Green', value: '#43a047' }, { id: colorId('brown'), name: 'Brown', value: '#795548' }],
  solution: [
    [null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null],
    [null, null, colorId('red'), colorId('red'), colorId('red'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null],
    [null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), null, null, null, colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), null, null, null],
    [null, null, null, colorId('brown'), colorId('brown'), null, null, null, null, null, colorId('brown'), colorId('brown'), null, null, null],
    [null, null, null, colorId('brown'), colorId('brown'), null, null, null, null, null, colorId('brown'), colorId('brown'), null, null, null],
    [null, null, colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), null, null],
    [colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green')],
  ],
  rowClues: [
    [{ length: 5, colorId: colorId('red') }],
    [{ length: 9, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('white') }, { length: 3, colorId: colorId('red') }, { length: 1, colorId: colorId('white') }, { length: 4, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 1, colorId: colorId('white') }, { length: 3, colorId: colorId('red') }, { length: 1, colorId: colorId('white') }, { length: 5, colorId: colorId('red') }],
    [{ length: 13, colorId: colorId('red') }],
    [{ length: 13, colorId: colorId('red') }],
    [{ length: 11, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('brown') }],
    [{ length: 7, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('brown') }, { length: 2, colorId: colorId('brown') }],
    [{ length: 3, colorId: colorId('brown') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('brown') }, { length: 2, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('brown') }, { length: 2, colorId: colorId('brown') }],
    [{ length: 3, colorId: colorId('brown') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 15, colorId: colorId('green') }],
  ],
  colClues: [
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 3, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 5, colorId: colorId('red') }, { length: 4, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 6, colorId: colorId('red') }, { length: 6, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('white') }, { length: 3, colorId: colorId('red') }, { length: 4, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 7, colorId: colorId('red') }, { length: 2, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 7, colorId: colorId('red') }, { length: 2, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 7, colorId: colorId('red') }, { length: 2, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('white') }, { length: 3, colorId: colorId('red') }, { length: 4, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 7, colorId: colorId('red') }, { length: 6, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 6, colorId: colorId('red') }, { length: 4, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 6, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }, { length: 1, colorId: colorId('green') }],
    [{ length: 5, colorId: colorId('red') }, { length: 1, colorId: colorId('green') }],
    [{ length: 3, colorId: colorId('red') }, { length: 1, colorId: colorId('green') }],
  ],
};

/** Color 15×15 puzzle: Sunset 15├ù15. */
// prettier-ignore
const sunsetDefinition: PuzzleDefinition = {
  id: 'color-sunset-15x15',
  name: 'Sunset 15├ù15',
  kind: 'color',
  rows: 15,
  cols: 15,
  palette: [{ id: colorId('orange'), name: 'Orange', value: '#ff9800' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }, { id: colorId('blue'), name: 'Blue', value: '#1e88e5' }, { id: colorId('red'), name: 'Red', value: '#e53935' }],
  solution: [
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('blue'), colorId('blue'), colorId('blue'), null],
    [colorId('blue'), colorId('blue'), colorId('blue'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('blue'), colorId('blue'), null],
    [colorId('blue'), colorId('blue'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('blue'), colorId('blue'), colorId('blue')],
    [colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red'), null],
    [colorId('red'), colorId('red'), colorId('red'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('red'), colorId('red'), colorId('red'), null],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('yellow'), colorId('yellow'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
    [colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red')],
  ],
  rowClues: [
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 15, colorId: colorId('blue') }],
    [{ length: 6, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 6, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 7, colorId: colorId('orange') }, { length: 3, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('blue') }, { length: 9, colorId: colorId('orange') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 10, colorId: colorId('orange') }, { length: 3, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 6, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 8, colorId: colorId('yellow') }, { length: 3, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 6, colorId: colorId('yellow') }, { length: 5, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('red') }, { length: 4, colorId: colorId('yellow') }, { length: 6, colorId: colorId('red') }],
    [{ length: 6, colorId: colorId('red') }, { length: 2, colorId: colorId('yellow') }, { length: 7, colorId: colorId('red') }],
    [{ length: 15, colorId: colorId('red') }],
    [{ length: 15, colorId: colorId('red') }],
    [{ length: 15, colorId: colorId('red') }],
  ],
  colClues: [
    [{ length: 7, colorId: colorId('blue') }, { length: 8, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('blue') }, { length: 8, colorId: colorId('red') }],
    [{ length: 6, colorId: colorId('blue') }, { length: 2, colorId: colorId('orange') }, { length: 7, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 6, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 3, colorId: colorId('yellow') }, { length: 5, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 4, colorId: colorId('yellow') }, { length: 4, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('blue') }, { length: 4, colorId: colorId('orange') }, { length: 5, colorId: colorId('yellow') }, { length: 3, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('blue') }, { length: 4, colorId: colorId('orange') }, { length: 5, colorId: colorId('yellow') }, { length: 3, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('blue') }, { length: 4, colorId: colorId('orange') }, { length: 4, colorId: colorId('yellow') }, { length: 4, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 3, colorId: colorId('yellow') }, { length: 5, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 4, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 6, colorId: colorId('red') }],
    [{ length: 5, colorId: colorId('blue') }, { length: 3, colorId: colorId('orange') }, { length: 7, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('blue') }, { length: 8, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('blue') }, { length: 8, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('blue') }, { length: 1, colorId: colorId('blue') }, { length: 6, colorId: colorId('red') }],
  ],
};

function assertValid(def: PuzzleDefinition): ValidatedPuzzle {
  const result = validatePuzzleDefinition(def);
  if (Array.isArray(result)) {
    throw new Error(
    `Sample puzzle "${def.id}" failed validation:\n${result.map((e) => `  - ${e.message}`).join('\n')}`,
    );
  }
  return result;
}

/** Validated Anchor 15├ù15. */
export const anchorPuzzle: ValidatedPuzzle = assertValid(anchorDefinition);

/** Validated Cat 15├ù15. */
export const catPuzzle: ValidatedPuzzle = assertValid(catDefinition);

/** Validated House 15├ù15. */
export const housePuzzle: ValidatedPuzzle = assertValid(houseDefinition);

/** Validated Skull 15├ù15. */
export const skullPuzzle: ValidatedPuzzle = assertValid(skullDefinition);

/** Validated Tree 15├ù15. */
export const treePuzzle: ValidatedPuzzle = assertValid(treeDefinition);

/** Validated Sailboat 15├ù15. */
export const boatPuzzle: ValidatedPuzzle = assertValid(boatDefinition);

/** Validated Cherry 15├ù15. */
export const cherryPuzzle: ValidatedPuzzle = assertValid(cherryDefinition);

/** Validated Flower 15├ù15. */
export const flowerPuzzle: ValidatedPuzzle = assertValid(flowerDefinition);

/** Validated Mushroom 15├ù15. */
export const mushroomPuzzle: ValidatedPuzzle = assertValid(mushroomDefinition);

/** Validated Sunset 15├ù15. */
export const sunsetPuzzle: ValidatedPuzzle = assertValid(sunsetDefinition);

/** Returns all 15x15 sample puzzles. */
export function getSamplePuzzles15x15(): ValidatedPuzzle[] {
  return [
    anchorPuzzle,
    catPuzzle,
    housePuzzle,
    skullPuzzle,
    treePuzzle,
    boatPuzzle,
    cherryPuzzle,
    flowerPuzzle,
    mushroomPuzzle,
    sunsetPuzzle,
  ];
}
