import type { PuzzleDefinition, ValidatedPuzzle } from '../types';
import { colorId } from '../types';
import { validatePuzzleDefinition } from '../engine/validation';

/** B&W 20×20 puzzle: Castle 20×20. */
// prettier-ignore
const castleDefinition: PuzzleDefinition = {
  id: 'bw-castle-20x20',
  name: 'Castle 20×20',
  kind: 'bw',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, colorId('black'), null, colorId('black'), null, null, null, null, null, null, null, null, null, null, null, null, null, colorId('black'), null, colorId('black')],
    [null, colorId('black'), null, colorId('black'), null, null, null, null, null, null, null, null, null, null, null, null, null, colorId('black'), null, colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, colorId('black'), null, null, colorId('black'), null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, colorId('black'), null, null, colorId('black'), null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
  ],
  rowClues: [
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 6, colorId: colorId('black') }, { length: 5, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
  ],
  colClues: [
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
  ],
};

/** B&W 20×20 puzzle: Dog 20×20. */
// prettier-ignore
const dogDefinition: PuzzleDefinition = {
  id: 'bw-dog-20x20',
  name: 'Dog 20×20',
  kind: 'bw',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, null, null],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, null],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null, null, null],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, colorId('black'), null, null, colorId('black'), colorId('black'), null, colorId('black'), null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, colorId('black'), null, null, colorId('black'), colorId('black'), null, colorId('black'), null, null],
  ],
  rowClues: [
    [{ length: 5, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 7, colorId: colorId('black') }, { length: 9, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 10, colorId: colorId('black') }],
    [{ length: 12, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 13, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }, { length: 6, colorId: colorId('black') }],
    [{ length: 12, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
  ],
  colClues: [
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 15, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 7, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 11, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 5, colorId: colorId('black') }, { length: 9, colorId: colorId('black') }],
    [{ length: 14, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
    [{ length: 9, colorId: colorId('black') }],
  ],
};

/** B&W 20×20 puzzle: Guitar 20×20. */
// prettier-ignore
const guitarDefinition: PuzzleDefinition = {
  id: 'bw-guitar-20x20',
  name: 'Guitar 20×20',
  kind: 'bw',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, null, null, null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
  ],
  colClues: [
    [],
    [],
    [],
    [],
    [],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 6, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 8, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 16, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 16, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 8, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 6, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [],
    [],
    [],
    [],
    [],
  ],
};

/** B&W 20×20 puzzle: Lighthouse 20×20. */
// prettier-ignore
const lighthouseDefinition: PuzzleDefinition = {
  id: 'bw-lighthouse-20x20',
  name: 'Lighthouse 20×20',
  kind: 'bw',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, colorId('black'), colorId('black'), null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), null, colorId('black'), colorId('black'), null, colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black')],
    [null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null],
    [null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null],
  ],
  rowClues: [
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
  ],
  colClues: [
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 20, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }, { length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
  ],
};

/** B&W 20×20 puzzle: Rocket 20×20. */
// prettier-ignore
const rocketDefinition: PuzzleDefinition = {
  id: 'bw-rocket-20x20',
  name: 'Rocket 20×20',
  kind: 'bw',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('black'), name: 'Black', value: '#000000' }],
  solution: [
    [null, null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null],
    [null, null, null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, null, null],
    [null, null, null, colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, colorId('black'), colorId('black'), null, null, null],
    [null, null, colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), null, null],
    [null, colorId('black'), colorId('black'), null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, colorId('black'), colorId('black'), null],
    [null, null, null, null, null, null, colorId('black'), colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), colorId('black'), null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('black'), colorId('black'), null, null, colorId('black'), colorId('black'), null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }],
    [{ length: 6, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 8, colorId: colorId('black') }],
    [{ length: 10, colorId: colorId('black') }],
    [{ length: 12, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 8, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 8, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
    [{ length: 3, colorId: colorId('black') }, { length: 3, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }, { length: 2, colorId: colorId('black') }],
  ],
  colClues: [
    [],
    [{ length: 1, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 14, colorId: colorId('black') }],
    [{ length: 17, colorId: colorId('black') }],
    [{ length: 17, colorId: colorId('black') }],
    [{ length: 4, colorId: colorId('black') }, { length: 14, colorId: colorId('black') }],
    [{ length: 18, colorId: colorId('black') }],
    [{ length: 16, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 2, colorId: colorId('black') }],
    [{ length: 1, colorId: colorId('black') }],
    [],
  ],
};

/** Color 20×20 puzzle: Cactus 20×20. */
// prettier-ignore
const cactusDefinition: PuzzleDefinition = {
  id: 'color-cactus-20x20',
  name: 'Cactus 20×20',
  kind: 'color',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('green'), name: 'Green', value: '#43a047' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }, { id: colorId('brown'), name: 'Brown', value: '#795548' }, { id: colorId('red'), name: 'Red', value: '#e53935' }],
  solution: [
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null],
    [null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null],
    [null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null],
    [null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, colorId('green'), colorId('green'), null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('red'), colorId('yellow'), colorId('red'), colorId('red'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('red'), colorId('yellow'), colorId('yellow'), colorId('red'), colorId('red'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('red'), colorId('yellow'), colorId('red'), colorId('red'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 8, colorId: colorId('green') }, { length: 2, colorId: colorId('green') }],
    [{ length: 8, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 2, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('brown') }],
    [{ length: 4, colorId: colorId('brown') }],
    [{ length: 6, colorId: colorId('brown') }],
  ],
  colClues: [
    [],
    [],
    [],
    [{ length: 5, colorId: colorId('green') }],
    [{ length: 5, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }, { length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('green') }, { length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('red') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('green') }, { length: 3, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('green') }, { length: 3, colorId: colorId('red') }, { length: 2, colorId: colorId('green') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('green') }, { length: 3, colorId: colorId('red') }, { length: 3, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('green') }, { length: 1, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 1, colorId: colorId('green') }],
    [{ length: 5, colorId: colorId('green') }],
    [{ length: 5, colorId: colorId('green') }],
    [],
    [],
    [],
  ],
};

/** Color 20×20 puzzle: Cupcake 20×20. */
// prettier-ignore
const cupcakeDefinition: PuzzleDefinition = {
  id: 'color-cupcake-20x20',
  name: 'Cupcake 20×20',
  kind: 'color',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('pink'), name: 'Pink', value: '#e91e9f' }, { id: colorId('white'), name: 'White', value: '#ffffff' }, { id: colorId('brown'), name: 'Brown', value: '#795548' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }],
  solution: [
    [null, null, null, null, null, null, null, null, colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null, null],
    [null, null, null, null, null, colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), null, null, null, null, null],
    [null, null, null, null, colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('pink'), null, null, null, null],
    [null, null, null, colorId('pink'), colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('white'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), null, null, null],
    [null, null, colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), null, null],
    [null, null, colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), null, null],
    [null, null, null, colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), colorId('pink'), null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null],
    [null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), colorId('brown'), null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 4, colorId: colorId('yellow') }],
    [{ length: 6, colorId: colorId('yellow') }],
    [{ length: 4, colorId: colorId('red') }],
    [{ length: 6, colorId: colorId('red') }],
    [{ length: 10, colorId: colorId('pink') }],
    [{ length: 2, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 2, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 2, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 3, colorId: colorId('pink') }],
    [{ length: 3, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 2, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 2, colorId: colorId('pink') }, { length: 1, colorId: colorId('white') }, { length: 4, colorId: colorId('pink') }],
    [{ length: 16, colorId: colorId('pink') }],
    [{ length: 16, colorId: colorId('pink') }],
    [{ length: 14, colorId: colorId('pink') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 12, colorId: colorId('brown') }],
    [{ length: 10, colorId: colorId('brown') }],
    [{ length: 8, colorId: colorId('brown') }],
  ],
  colClues: [
    [],
    [],
    [{ length: 2, colorId: colorId('pink') }],
    [{ length: 4, colorId: colorId('pink') }],
    [{ length: 5, colorId: colorId('pink') }, { length: 8, colorId: colorId('brown') }],
    [{ length: 6, colorId: colorId('pink') }, { length: 9, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('pink') }, { length: 2, colorId: colorId('white') }, { length: 3, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('red') }, { length: 6, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }, { length: 6, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('pink') }, { length: 2, colorId: colorId('white') }, { length: 3, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }, { length: 6, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('red') }, { length: 6, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('pink') }, { length: 2, colorId: colorId('white') }, { length: 3, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 6, colorId: colorId('pink') }, { length: 10, colorId: colorId('brown') }],
    [{ length: 6, colorId: colorId('pink') }, { length: 9, colorId: colorId('brown') }],
    [{ length: 5, colorId: colorId('pink') }, { length: 8, colorId: colorId('brown') }],
    [{ length: 4, colorId: colorId('pink') }],
    [{ length: 2, colorId: colorId('pink') }],
    [],
    [],
  ],
};

/** Color 20×20 puzzle: Parrot 20×20. */
// prettier-ignore
const parrotDefinition: PuzzleDefinition = {
  id: 'color-parrot-20x20',
  name: 'Parrot 20×20',
  kind: 'color',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('green'), name: 'Green', value: '#43a047' }, { id: colorId('blue'), name: 'Blue', value: '#1e88e5' }, { id: colorId('black'), name: 'Black', value: '#212121' }, { id: colorId('white'), name: 'White', value: '#ffffff' }],
  solution: [
    [null, null, null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null],
    [null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('white'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('white'), colorId('white'), colorId('white'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('black'), colorId('black'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('red'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, null],
    [null, null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, null, null],
    [null, null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, null, null],
    [null, null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [null, colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, null],
    [colorId('green'), colorId('green'), colorId('green'), colorId('green'), null, null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, null, null, null, null, null, null, null],
    [colorId('green'), colorId('green'), colorId('green'), null, null, null, null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), null, null, null, null, null, null, null, null],
    [colorId('green'), colorId('green'), null, null, null, null, null, null, null, null, colorId('blue'), colorId('blue'), null, null, null, null, null, null, null, null],
    [colorId('green'), null, null, null, null, null, null, null, null, null, null, colorId('blue'), null, null, null, null, null, null, null, null],
  ],
  rowClues: [
    [{ length: 4, colorId: colorId('red') }],
    [{ length: 8, colorId: colorId('red') }],
    [{ length: 10, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 4, colorId: colorId('red') }, { length: 2, colorId: colorId('white') }, { length: 7, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 3, colorId: colorId('white') }, { length: 7, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 2, colorId: colorId('black') }, { length: 8, colorId: colorId('red') }],
    [{ length: 13, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 10, colorId: colorId('red') }],
    [{ length: 7, colorId: colorId('green') }, { length: 1, colorId: colorId('red') }],
    [{ length: 8, colorId: colorId('green') }],
    [{ length: 8, colorId: colorId('green') }],
    [{ length: 9, colorId: colorId('green') }],
    [{ length: 9, colorId: colorId('green') }],
    [{ length: 10, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('green') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('green') }, { length: 3, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 1, colorId: colorId('green') }, { length: 1, colorId: colorId('blue') }],
  ],
  colClues: [
    [{ length: 4, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('red') }, { length: 4, colorId: colorId('green') }],
    [{ length: 6, colorId: colorId('red') }, { length: 4, colorId: colorId('green') }],
    [{ length: 8, colorId: colorId('red') }, { length: 5, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('red') }, { length: 1, colorId: colorId('white') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('red') }, { length: 6, colorId: colorId('green') }],
    [{ length: 3, colorId: colorId('red') }, { length: 2, colorId: colorId('white') }, { length: 1, colorId: colorId('black') }, { length: 3, colorId: colorId('red') }, { length: 6, colorId: colorId('green') }],
    [{ length: 4, colorId: colorId('red') }, { length: 2, colorId: colorId('white') }, { length: 4, colorId: colorId('red') }, { length: 6, colorId: colorId('green') }, { length: 1, colorId: colorId('blue') }],
    [{ length: 10, colorId: colorId('red') }, { length: 6, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 10, colorId: colorId('red') }, { length: 6, colorId: colorId('green') }, { length: 3, colorId: colorId('blue') }],
    [{ length: 10, colorId: colorId('red') }, { length: 4, colorId: colorId('green') }, { length: 4, colorId: colorId('blue') }],
    [{ length: 9, colorId: colorId('red') }, { length: 2, colorId: colorId('green') }],
    [{ length: 10, colorId: colorId('red') }],
    [{ length: 8, colorId: colorId('red') }],
    [{ length: 6, colorId: colorId('red') }],
    [],
    [],
    [],
    [],
  ],
};

/** Color 20×20 puzzle: Rainbow 20×20. */
// prettier-ignore
const rainbowDefinition: PuzzleDefinition = {
  id: 'color-rainbow-20x20',
  name: 'Rainbow 20×20',
  kind: 'color',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('orange'), name: 'Orange', value: '#ff9800' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }, { id: colorId('green'), name: 'Green', value: '#43a047' }, { id: colorId('blue'), name: 'Blue', value: '#1e88e5' }],
  solution: [
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null, null],
    [null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red'), colorId('red'), null],
    [null, null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('orange'), colorId('red'), null],
    [null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red')],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('green'), colorId('green'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('green'), colorId('green'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('green'), colorId('green'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('green'), colorId('green'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('green'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('red'), null, null],
    [null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red')],
    [null, null, colorId('red'), colorId('orange'), colorId('orange'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('orange'), colorId('orange'), colorId('red'), null],
    [null, null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red'), colorId('red'), null],
    [null, null, null, colorId('red'), colorId('red'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('orange'), colorId('red'), colorId('red'), colorId('red'), null, null],
    [null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null],
    [null, null, null, null, null, null, null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
  rowClues: [
    [],
    [{ length: 6, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 10, colorId: colorId('orange') }, { length: 3, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 12, colorId: colorId('orange') }, { length: 3, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 11, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 11, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 8, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 10, colorId: colorId('green') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 6, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 6, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('yellow') }, { length: 10, colorId: colorId('green') }, { length: 1, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 8, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 11, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 11, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 12, colorId: colorId('orange') }, { length: 3, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 10, colorId: colorId('orange') }, { length: 3, colorId: colorId('red') }],
    [{ length: 12, colorId: colorId('red') }],
    [{ length: 6, colorId: colorId('red') }],
    [],
  ],
  colClues: [
    [],
    [{ length: 8, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 6, colorId: colorId('orange') }, { length: 3, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 10, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 3, colorId: colorId('orange') }, { length: 6, colorId: colorId('yellow') }, { length: 3, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 3, colorId: colorId('yellow') }, { length: 4, colorId: colorId('green') }, { length: 3, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 6, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('yellow') }, { length: 6, colorId: colorId('green') }, { length: 2, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 3, colorId: colorId('yellow') }, { length: 4, colorId: colorId('green') }, { length: 3, colorId: colorId('yellow') }, { length: 2, colorId: colorId('orange') }, { length: 1, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('orange') }, { length: 10, colorId: colorId('yellow') }, { length: 1, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 10, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 2, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 6, colorId: colorId('red') }, { length: 2, colorId: colorId('orange') }, { length: 2, colorId: colorId('red') }],
    [{ length: 3, colorId: colorId('red') }, { length: 3, colorId: colorId('red') }],
    [{ length: 1, colorId: colorId('red') }, { length: 1, colorId: colorId('red') }],
  ],
};

/** Color 20×20 puzzle: Robot 20×20. */
// prettier-ignore
const robotDefinition: PuzzleDefinition = {
  id: 'color-robot-20x20',
  name: 'Robot 20×20',
  kind: 'color',
  rows: 20,
  cols: 20,
  palette: [{ id: colorId('silver'), name: 'Silver', value: '#90a4ae' }, { id: colorId('red'), name: 'Red', value: '#e53935' }, { id: colorId('blue'), name: 'Blue', value: '#1e88e5' }, { id: colorId('yellow'), name: 'Yellow', value: '#fdd835' }],
  solution: [
    [null, null, null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, null, null],
    [null, null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), null, colorId('red'), colorId('red'), colorId('red'), colorId('red'), null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('yellow'), colorId('yellow'), colorId('yellow'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, null],
    [null, null, null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, null, null],
    [null, null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, null, null, null],
    [null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, null, null],
    [null, null, null, colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), null, null, null],
    [null, null, null, colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), null, null, null],
    [null, null, null, colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, colorId('blue'), colorId('blue'), null, null, null],
    [null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, null, null],
    [null, null, null, null, colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), colorId('blue'), null, null, null, null],
    [null, null, null, null, null, colorId('blue'), colorId('blue'), null, null, null, null, null, null, colorId('blue'), colorId('blue'), null, null, null, null, null],
    [null, null, null, null, null, colorId('blue'), colorId('blue'), null, null, null, null, null, null, colorId('blue'), colorId('blue'), null, null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
    [null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null, colorId('silver'), colorId('silver'), colorId('silver'), colorId('silver'), null, null, null, null],
  ],
  rowClues: [
    [{ length: 8, colorId: colorId('silver') }],
    [{ length: 10, colorId: colorId('silver') }],
    [{ length: 12, colorId: colorId('silver') }],
    [{ length: 2, colorId: colorId('silver') }, { length: 4, colorId: colorId('red') }, { length: 4, colorId: colorId('silver') }],
    [{ length: 2, colorId: colorId('silver') }, { length: 4, colorId: colorId('red') }, { length: 4, colorId: colorId('silver') }],
    [{ length: 12, colorId: colorId('silver') }],
    [{ length: 4, colorId: colorId('silver') }, { length: 3, colorId: colorId('yellow') }, { length: 5, colorId: colorId('silver') }],
    [{ length: 10, colorId: colorId('silver') }],
    [{ length: 8, colorId: colorId('silver') }],
    [{ length: 12, colorId: colorId('blue') }],
    [{ length: 14, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 8, colorId: colorId('blue') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 8, colorId: colorId('blue') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 8, colorId: colorId('blue') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 14, colorId: colorId('blue') }],
    [{ length: 12, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 2, colorId: colorId('blue') }, { length: 2, colorId: colorId('blue') }],
    [{ length: 4, colorId: colorId('silver') }, { length: 4, colorId: colorId('silver') }],
    [{ length: 4, colorId: colorId('silver') }, { length: 4, colorId: colorId('silver') }],
  ],
  colClues: [
    [],
    [],
    [],
    [{ length: 5, colorId: colorId('blue') }],
    [{ length: 5, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 7, colorId: colorId('silver') }, { length: 2, colorId: colorId('blue') }, { length: 4, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 4, colorId: colorId('silver') }, { length: 9, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 2, colorId: colorId('red') }, { length: 4, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('silver') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('silver') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 2, colorId: colorId('red') }, { length: 1, colorId: colorId('silver') }, { length: 1, colorId: colorId('yellow') }, { length: 2, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }],
    [{ length: 3, colorId: colorId('silver') }, { length: 4, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }],
    [{ length: 9, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 9, colorId: colorId('silver') }, { length: 9, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 7, colorId: colorId('silver') }, { length: 2, colorId: colorId('blue') }, { length: 4, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 5, colorId: colorId('silver') }, { length: 7, colorId: colorId('blue') }, { length: 2, colorId: colorId('silver') }],
    [{ length: 5, colorId: colorId('blue') }],
    [],
    [],
    [],
  ],
};

function assertValid(def: PuzzleDefinition): ValidatedPuzzle {
  const result = validatePuzzleDefinition(def);
  if (Array.isArray(result)) {
    throw new Error(
      `Sample puzzle "${def.id}" failed validation:\n${result.map((e) => `  - ${e.message}`).join('\n')}`,
    );
  }
  return result;
}

/** Validated Castle 20×20. */
export const castlePuzzle: ValidatedPuzzle = assertValid(castleDefinition);

/** Validated Dog 20×20. */
export const dogPuzzle: ValidatedPuzzle = assertValid(dogDefinition);

/** Validated Guitar 20×20. */
export const guitarPuzzle: ValidatedPuzzle = assertValid(guitarDefinition);

/** Validated Lighthouse 20×20. */
export const lighthousePuzzle: ValidatedPuzzle = assertValid(lighthouseDefinition);

/** Validated Rocket 20×20. */
export const rocketPuzzle: ValidatedPuzzle = assertValid(rocketDefinition);

/** Validated Cactus 20×20. */
export const cactusPuzzle: ValidatedPuzzle = assertValid(cactusDefinition);

/** Validated Cupcake 20×20. */
export const cupcakePuzzle: ValidatedPuzzle = assertValid(cupcakeDefinition);

/** Validated Parrot 20×20. */
export const parrotPuzzle: ValidatedPuzzle = assertValid(parrotDefinition);

/** Validated Rainbow 20×20. */
export const rainbowPuzzle: ValidatedPuzzle = assertValid(rainbowDefinition);

/** Validated Robot 20×20. */
export const robotPuzzle: ValidatedPuzzle = assertValid(robotDefinition);

/** Returns all 20x20 sample puzzles. */
export function getSamplePuzzles20x20(): ValidatedPuzzle[] {
  return [
    castlePuzzle,
    dogPuzzle,
    guitarPuzzle,
    lighthousePuzzle,
    rocketPuzzle,
    cactusPuzzle,
    cupcakePuzzle,
    parrotPuzzle,
    rainbowPuzzle,
    robotPuzzle,
  ];
}
